# Site settings
title: å‰£å´æ¢¨ã€…èŠ±ã®ã‚ªãƒ¼ãƒœã‚¨ç·´ç¿’æ›²
motto: >
  ğ„ å‰£å´æ¢¨ã€…èŠ±ã®ã‚ªãƒ¼ãƒœã‚¨ç·´ç¿’æ›²
description: > # this means to ignore newlines until "baseurl:"
  ~ â™ª Inevitable swaying, accompany with maples.
  WhiteTiger Field, Someday in the raining. ğ„‡
baseurl: "/maples" # the subpath of your site, e.g. /blog/
url: https://yohaneww.github.io # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter : rouge

# Author settings
author:
  name     : "Yohane"